### ISSUE TITLE
CSS implementation not working

### ISSUE THREAD

**Issue by Carmoruda** [Carmoruda/Webpage#1]
The implementation in the HTML file isn't working correctly. 

HTML file:

```HTML
<!DOCTYPE HTML>

<html lang="en">

<head>
<link rel="stylesheet" type="text/css" href="style.css" media=”screen” />
</head>


<h1 id="Praesent tristique magna sit">Praesent tristique magna sit</h1>
<h2>Vitae semper quis lectus nulla</h2>
```

CSS file:

```CSS
@font-face {
  font-family: Roboto;
  src: url("https://fonts.googleapis.com/css?family=Roboto");
}

.blue-text {
  color: #191cbd;
  font-size: 16px;
  font-family: Roboto;
}

h1 {
  color: #f5c527;
}

h2 {
  color: #442803;
}
```
